# -*- coding: utf-8 -*-
"""
Windows PE 파일 버전 정보(Version Resource) 생성 스크립트.
src/main.py의 APP_VERSION을 읽어 file_version_info.txt를 자동 생성합니다.
"""

import os
import re

def get_app_version():
    env_version = os.environ.get("VERSION", "").strip().lstrip("v")
    if env_version:
        return env_version
    main_py_path = os.path.join(os.path.dirname(__file__), 'src', 'main.py')
    version = "1.0.0"
    if os.path.exists(main_py_path):
        with open(main_py_path, 'r', encoding='utf-8') as f:
            content = f.read()
            match = re.search(r'APP_VERSION\s*=\s*["\']([^"\']+)["\']', content)
            if match:
                version = match.group(1)
    return version

def parse_version_tuple(version_str):
    parts = []
    for p in version_str.split('.'):
        digits = re.findall(r'\d+', p)
        if digits:
            parts.append(int(digits[0]))
        else:
            parts.append(0)
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])

def generate():
    version_str = get_app_version()
    v_tuple = parse_version_tuple(version_str)
    version_dotted = f"{v_tuple[0]}.{v_tuple[1]}.{v_tuple[2]}.{v_tuple[3]}"

    content = f"""# UTF-8
# Auto-generated by generate_version_info.py
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={v_tuple},
    prodvers={v_tuple},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '040904B0',
          [
            StringStruct('CompanyName', 'RubyKor'),
            StringStruct('FileDescription', 'Webtoon Downloader & Offline HTML Viewer'),
            StringStruct('FileVersion', '{version_dotted}'),
            StringStruct('InternalName', 'WebtoonDownloader'),
            StringStruct('LegalCopyright', 'Copyright (C) 2024-2026 RubyKor. All rights reserved.'),
            StringStruct('OriginalFilename', 'Webtoon Downloader.exe'),
            StringStruct('ProductName', 'Webtoon Downloader'),
            StringStruct('ProductVersion', '{version_str}')
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""
    output_path = os.path.join(os.path.dirname(__file__), 'file_version_info.txt')
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"[OK] Generated file_version_info.txt (Version: {version_str} -> {v_tuple})")

if __name__ == '__main__':
    generate()
